//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialProvider.GitHub {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CredentialProvider.GitHub.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CommandLineArgs {
            get {
                return ResourceManager.GetString("CommandLineArgs", resourceCulture);
            }
        }
        
        internal static string RunningInPlugin {
            get {
                return ResourceManager.GetString("RunningInPlugin", resourceCulture);
            }
        }
        
        internal static string RunningInStandAlone {
            get {
                return ResourceManager.GetString("RunningInStandAlone", resourceCulture);
            }
        }
        
        internal static string Redacted {
            get {
                return ResourceManager.GetString("Redacted", resourceCulture);
            }
        }
        
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password ", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string FaultedOnMessage {
            get {
                return ResourceManager.GetString("FaultedOnMessage", resourceCulture);
            }
        }
        
        internal static string PluginTimedOut {
            get {
                return ResourceManager.GetString("PluginTimedOut", resourceCulture);
            }
        }
    }
}
